### ISSUE TITLE
split messages in separate posts

### ISSUE THREAD

**Issue by rubo77** [turt2live/matrix-email-bot#12]
It would help if the main mail is in a separate post than the quoted part and separate from an email-footer

this way you could tidy up the matrix room with the redact buttons from duplicate quoted texts and footers if needed

**Comment by turt2live** [comment]
Replies should now be parsed out of the messages by default.

**Comment by rubo77** [comment]
This doesn't seem to work correctly yet.

Still only one post:

```
<freifunk@xxxxxx.de> Re: [Freifunk-keys] Neue Commits im Schlüssel Repository sollten jetzt auch im Matrix Raum ankommen
Replies sind jetzt extra😃

Am 25. Februar 2017 06:10:41 MEZ, schrieb freifunk@xxxxxxx.de:
>Test
>_______________________________________________
>Freifunk-Keys mailing list
>Freifunk-Keys@lists.xxxxxx.de
>https://lists.in-kiel.de/mailman/listinfo/freifunk-xxxxxx
```

**Comment by turt2live** [comment]
It appears as though the library I used doesn't support other languages very well. Reopening to explore other libraries.

**Comment by turt2live** [comment]
Now it should work. Let me know if you have any issues :)
