### ISSUE TITLE
Trigger as LDA/Alias, instead of SMTP

### ISSUE THREAD

**Issue by freelock** [turt2live/matrix-email-bot#15]
Hi,

Very interesting project!

Was wondering if you had considered making it load via a shell, providing some sort of executable that would get the email on stdin... If you're already running a mail server, it might make it far easier to set up than the current model of listening on port 25.

I can think of several ways this might be used:

- Postfix alias piped into executable
- Postfix entry in master.cf, as a "local delivery agent"
- Maildrop/Procmail filter hands off to executable

... this last bit would be most interesting, then you could set up a Sieve rule to forward to a Matrix room based on the email contents...

**Comment by turt2live** [comment]
Thanks for the suggestion! I don't know why, but that functionality slipped my mind. Definitely something I'll be adding.

**Comment by turt2live** [comment]
Added as of https://github.com/turt2live/matrix-email-bot/commit/c38b95b1fb079c155ca910d67a0c69a8b85b4824.

**Comment by freelock** [comment]
Great! I might have to give this a try...
